In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame()

In [3]:
print(df)

Empty DataFrame
Columns: []
Index: []

In [4]:
df = pd.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [14]:
df

    0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [6]:
print(df)

    0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

## Basic Functions

In [7]:
df.head(2)  #First 2 rows

   0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [8]:
df.tail(2)  #Last 2 rows

    0   1   2   3
2   9  10  11  12
3  13  14  15  16

In [9]:
df.shape  #Size of DataFrame

(4, 4)

## Slicing

In [10]:
df.iloc[2, 3]  #Prints data at 2,3

np.int64(12)

In [11]:
df.iloc[0:2, 1:3]  #Prints data at 0,1; 0,2; 1,1 and 1,2

   1  2
0  2  3
1  6  7

In [12]:
pd1 = pd.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]], columns=["A", "B", "C", "D"])

In [13]:
pd1

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16