In [2]:
import pandas as pd

## Read

In [5]:
df = pd.read_csv("c1.csv")

In [6]:
df

,timestamp,currency,name,cost,organization_id,project_id,project_name,organization_name,cost_in_major,date
0,1.730938e+09,usd,Other models,1.24845,org-YhEzzfPgPYe8I1EdtPrX66ah,proj_XFWyBKIsLOl1ZhHJfmZjTXSY,Jarvis,Personal,0.012485,2024-11-07
1,1.731024e+09,usd,Other models,1.42030,org-YhEzzfPgPYe8I1EdtPrX66ah,proj_XFWyBKIsLOl1ZhHJfmZjTXSY,Jarvis,Personal,0.014203,2024-11-08
2,1.731197e+09,usd,Other models,0.68225,org-YhEzzfPgPYe8I1EdtPrX66ah,proj_XFWyBKIsLOl1ZhHJfmZjTXSY,Jarvis,Personal,0.006822,2024-11-10
3,1.731456e+09,usd,Other models,0.19585,org-YhEzzfPgPYe8I1EdtPrX66ah,proj_XFWyBKIsLOl1ZhHJfmZjTXSY,Jarvis,Personal,0.001959,2024-11-13
4,1.731542e+09,usd,Other models,0.72120,org-YhEzzfPgPYe8I1EdtPrX66ah,proj_XFWyBKIsLOl1ZhHJfmZjTXSY,Jarvis,Personal,0.007212,2024-11-14

In [7]:
df.head(2)

,timestamp,currency,name,cost,organization_id,project_id,project_name,organization_name,cost_in_major,date
0,1.730938e+09,usd,Other models,1.24845,org-YhEzzfPgPYe8I1EdtPrX66ah,proj_XFWyBKIsLOl1ZhHJfmZjTXSY,Jarvis,Personal,0.012485,2024-11-07
1,1.731024e+09,usd,Other models,1.42030,org-YhEzzfPgPYe8I1EdtPrX66ah,proj_XFWyBKIsLOl1ZhHJfmZjTXSY,Jarvis,Personal,0.014203,2024-11-08

In [8]:
df.tail(2)

,timestamp,currency,name,cost,organization_id,project_id,project_name,organization_name,cost_in_major,date
3,1.731456e+09,usd,Other models,0.19585,org-YhEzzfPgPYe8I1EdtPrX66ah,proj_XFWyBKIsLOl1ZhHJfmZjTXSY,Jarvis,Personal,0.001959,2024-11-13
4,1.731542e+09,usd,Other models,0.72120,org-YhEzzfPgPYe8I1EdtPrX66ah,proj_XFWyBKIsLOl1ZhHJfmZjTXSY,Jarvis,Personal,0.007212,2024-11-14

In [16]:
print(df["cost_in_major"])

0    0.012485
1    0.014203
2    0.006822
3    0.001959
4    0.007212
Name: cost_in_major, dtype: float64

In [17]:
print(df["cost_in_major"].name)
print(df["cost_in_major"].dtype)

cost_in_major
float64

## Write

In [34]:
df = pd.DataFrame([[1, 2, 3, 4], [21, 342, 543, 23], [23, 765, 867, 230], [978, 23, 87, 1234]], columns=["A", "B", "C", "D"])

In [35]:
df.to_csv("c2.csv", index=False)  #Makes a new csv file

In [36]:
df

     A    B    C     D
0    1    2    3     4
1   21  342  543    23
2   23  765  867   230
3  978   23   87  1234