In [22]:
import pandas as pd

In [41]:
df1 = pd.DataFrame([[12,2,342], [423,1,54], [65,8,23]], columns=['A','B','C'])

In [36]:
df1

     A   B    C
0   12  29  342
1  423   1   54
2   65   8   23

In [37]:
df2 = pd.DataFrame([[9,2,3], [6,10,5], [4,8,5]], columns=['X','Y','Z'])

In [38]:
df2

   X   Y  Z
0  9   2  3
1  6  10  5
2  4   8  5

#### Only rows that will be printed will be the same for both B and Y

In [42]:
df3 = pd.merge(df1, df2, left_on='B', right_on='Y')

In [43]:
df3

    A  B    C  X  Y  Z
0  12  2  342  9  2  3
1  65  8   23  4  8  5