In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dict1 = {
    "name": ["Shail", "Raj", "Meet", "Mohit"],
    "marks": [90, 20, 43, 80],
    "city": ["Ahmedabad", "Kolkata", "Mumbai", "Ahmedabad"]
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

    name  marks       city
0  Shail     90  Ahmedabad
1    Raj     20    Kolkata
2   Meet     43     Mumbai
3  Mohit     80  Ahmedabad

read modifications

In [5]:
df.to_csv("emp.csv")

In [6]:
df.to_csv("emp_indexfalse.csv", index=False)

In [7]:
df.head(2)
# will print first 2 rows

    name  marks       city
0  Shail     90  Ahmedabad
1    Raj     20    Kolkata

In [8]:
df.tail(2)
# will print last 2 rows

    name  marks       city
2   Meet     43     Mumbai
3  Mohit     80  Ahmedabad

In [9]:
df.describe()
# will perform various numerical functions on numerical columns (currently only marks)

        marks
count   4.000
mean   58.250
std    32.541
min    20.000
25%    37.250
50%    61.500
75%    82.500
max    90.000

Read from csv

In [10]:
train = pd.read_csv("train.csv")

In [11]:
train

   Unnamed: 0.2 Unnamed: 0.1 Unnamed: 0  TrainNo  speed       city
0             0        first      first   123456     50  Ahmedabad
1             1       second     second   456321     20    Kolkata
2             2        third      third    98632     43     Mumbai
3             3       fourth     fourth   282047     80  Ahmedabad