In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name": ["Shail", "Raj", "Meet", "Mohit"],
    "marks": [90, 20, 43, 80],
    "city": ["Ahmedabad", "Kolkata", "Mumbai", "Ahmedabad"]
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

    name  marks       city
0  Shail     90  Ahmedabad
1    Raj     20    Kolkata
2   Meet     43     Mumbai
3  Mohit     80  Ahmedabad

read modifications

In [5]:
df.to_csv("emp.csv")

In [6]:
df.to_csv("emp_indexfalse.csv", index=False)

In [7]:
df.head(2)
# will print first 2 rows

    name  marks       city
0  Shail     90  Ahmedabad
1    Raj     20    Kolkata

In [8]:
df.tail(2)
# will print last 2 rows

    name  marks       city
2   Meet     43     Mumbai
3  Mohit     80  Ahmedabad

In [9]:
df.describe()
# will perform various numerical functions on numerical columns (currently only marks)

        marks
count   4.000
mean   58.250
std    32.541
min    20.000
25%    37.250
50%    61.500
75%    82.500
max    90.000

Read from csv

In [10]:
train = pd.read_csv("train.csv")

In [11]:
train

  Unnamed: 0.1 Unnamed: 0  TrainNo  speed       city
0        first      first   123456     50  Ahmedabad
1       second     second   456321     20    Kolkata
2        third      third    98632     43     Mumbai
3       fourth     fourth   282047     80  Ahmedabad

basic printing

In [12]:
train["speed"]

0    50
1    20
2    43
3    80
Name: speed, dtype: int64

In [13]:
train['speed'][0]

np.int64(50)

change value of an element (warning is given)

In [14]:
train['speed'][0] = 50

C:\Users\shail\AppData\Local\Temp\ipykernel_22232\2070240468.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['speed'][0] = 50

In [15]:
train

  Unnamed: 0.1 Unnamed: 0  TrainNo  speed       city
0        first      first   123456     50  Ahmedabad
1       second     second   456321     20    Kolkata
2        third      third    98632     43     Mumbai
3       fourth     fourth   282047     80  Ahmedabad

put data into csv file

In [16]:
train.to_csv('train.csv')

change value of index

In [17]:
train.index = ['first', 'second', 'third', 'fourth']

In [18]:
train

       Unnamed: 0.1 Unnamed: 0  TrainNo  speed       city
first         first      first   123456     50  Ahmedabad
second       second     second   456321     20    Kolkata
third         third      third    98632     43     Mumbai
fourth       fourth     fourth   282047     80  Ahmedabad

delete duplicated column

In [19]:
train.drop(columns=['Unnamed: 0'])

       Unnamed: 0.1  TrainNo  speed       city
first         first   123456     50  Ahmedabad
second       second   456321     20    Kolkata
third         third    98632     43     Mumbai
fourth       fourth   282047     80  Ahmedabad

series

In [24]:
ser = pd.Series(np.random.rand(30))

In [25]:
ser

0     0.996238
1     0.895313
2     0.041762
3     0.690015
4     0.466580
5     0.617819
6     0.995173
7     0.481930
8     0.766745
9     0.891211
10    0.829212
11    0.063716
12    0.764821
13    0.644292
14    0.896207
15    0.566581
16    0.136903
17    0.360278
18    0.184535
19    0.941948
20    0.936424
21    0.242164
22    0.153374
23    0.945826
24    0.627710
25    0.023710
26    0.117401
27    0.121445
28    0.285928
29    0.771912
dtype: float64

In [26]:
type(ser)

pandas.core.series.Series

series

In [30]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))

In [28]:
newdf

            0         1         2         3         4
0    0.169778  0.214625  0.607758  0.422127  0.428387
1    0.352741  0.686819  0.493164  0.619312  0.631620
2    0.725251  0.205657  0.843965  0.357602  0.729668
3    0.184107  0.776903  0.185451  0.730343  0.597327
4    0.343621  0.478700  0.460607  0.755299  0.650684
..        ...       ...       ...       ...       ...
329  0.560913  0.723744  0.289973  0.042009  0.458823
330  0.381731  0.498375  0.608180  0.598867  0.504939
331  0.536980  0.013386  0.585921  0.101052  0.466055
332  0.081293  0.544590  0.843276  0.913583  0.574006
333  0.208587  0.081745  0.270407  0.022941  0.442727

[334 rows x 5 columns]